server:
  port: 8081
spring:
  application:
    name: item-service
  datasource:
     url: jdbc:mysql:///luxury
     username: root
     password: 123456
  cloud:
    refresh:
      refreshable: none
eureka:
  client:
    service-url:
      defaultZone: http://localhost:10086/eureka
  instance:
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 15
mybatis:
  type-aliases-package: cn.luxury.item.pojo
